repository:
  # See https://docs.github.com/en/rest/reference/repos#update-branch-protection for more information
  branches:
    - name: main
      protection:
        required_status_checks:
          strict: true
          contexts:
            - Test
        enforce_admins: true
        required_pull_request_reviews:
          required_approving_review_count: 1
          dismiss_stale_reviews: true
          require_code_owner_reviews: true
        restrictions: null
